services:
    main_user.registration.form.type:
        class: Users\UsersBundle\Form\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: main_user_registration }

    user.registration_listener:
       class: Users\UsersBundle\EventListener\RegistrationListener
       arguments: [@router]
       tags:
           - { name: kernel.event_subscriber }
