<?php

namespace Donations\DonationsBundle\Repository;

/**
 * DonationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonationsRepository extends \Doctrine\ORM\EntityRepository
{
    /*
  public function getAvailableDon(){
    $query = $this->createQueryBuilder('d')
    ->leftJoin('d.associationsask','a')
    ->addSelect('a')
    ->where('d.available = 1')
    ->getQuery();

    return $query->getResult();
  }
     */
}
