<?php

namespace Donations\DonationsBundle\Repository;

/**
 * DonationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonationsRepository extends \Doctrine\ORM\EntityRepository
{
}
